# Even Fibonacci numbers.

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def calculate(max_range):
    first_number = 1
    second_number = 2
    result_sum = 2

    while second_number < max_range:

        aux_number = first_number + second_number

        if aux_number % 2 == 0:
            result_sum += aux_number

        first_number = second_number
        second_number = aux_number

    return result_sum  # return result.


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print("Even Fibonacci numbers, Result: " + str(calculate(4000000)))

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
